try6

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,8 +19,8 @@ jobs:
       - name: Log in to DockerHub
         uses: docker/login-action@v3
         with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_TOKEN }}
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       - name: Build and Push Docker Image
         uses: docker/build-push-action@v5
@@ -28,9 +28,16 @@ jobs:
           context: helm/rick-and-morty-api
           file: helm/rick-and-morty-api/Dockerfile
           push: true
-          tags: docker.io/silverdeath366/rickmorty-app:latest
+          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/rickmorty-app:latest
 
-      - name: Deploy to Kubernetes
+      - name: Create KinD Cluster
+        uses: helm/kind-action@v1.5.0
+
+      - name: Helm Upgrade & Install
         run: |
-          kubectl config set-context --current --namespace=default
           helm upgrade --install rickmorty helm/rick-and-morty-api
+
+      - name: Test API Healthcheck
+        run: |
+          sleep 10  # wait for pod to become ready
+          curl --fail http://localhost/healthcheck || (echo "❌ healthcheck failed" && exit 1)
